Fix syntactic issue

diff --git a/auto/health-check b/auto/health-check
--- a/auto/health-check
+++ b/auto/health-check
@@ -1,9 +1,9 @@
-#!/bin/sh
+#!/bin/bash -e
 
 ENV=$1
 PORT=$2
 PROJECT=$3
 
-URL="http://www.${ENV}.example.com"
+DOMAIN="www.${ENV}.example.com"
 
-curl -Is $URL:$PORT/$PROJECT/ > /dev/null && echo "[INFO] The remote site $URL:$PORT/$PROJECT/ is healthy and good to go..." || echo "[INFO] The remote side is failed, please check..."
+curl -Is http://$DOMAIN:$PORT/$PROJECT/ > /dev/null && echo "[INFO] The remote site http://$DOMAIN:$PORT/$PROJECT/ is healthy and good to go..." || echo "[INFO] The remote side is failed, please check..."
